## Z test using ( one sample test and two sample test )

In [1]:
import math
from scipy.stats import norm
#Sample data
sample_mean = 169.5
population_mean = 168
population_std_dev = 3.9
sample_size = 36
alpha = 0.05
tail = 'right'
#standard error
standard_error = population_std_dev / math.sqrt(sample_size)
#Z-score
z_score = (sample_mean - population_mean) / standard_error
#P-value based on type of test
if tail == 'two':
    p_value = 2*(1 - norm.cdf(abs(z_score)))
    print(norm.cdf(abs(z_score)))
elif tail == 'left':
    p_value = norm.cdf(z_score)
    print(norm.cdf(abs(z_score)))
elif tail == 'right':
    p_value = 1 - norm.cdf(z_score)
    print(norm.cdf(abs(z_score)))
else:
    raise ValueError("tail must be 'two', 'left', or 'right'")

#output
if p_value < alpha:
    conclusion = "Reject the null hypothesis"
else:
    conclusion = "Fail to reject the null hypothesis"

print(f"Z-score: {z_score:.4f}")
print(f"P-value: {p_value:.4f}")
print(f"Conclusion: {conclusion}")

0.9894918718862407
Z-score: 2.3077
P-value: 0.0105
Conclusion: Reject the null hypothesis


In [1]:
#T-test
from scipy import stats
# Significance level
alpha = 0.05
# One-sample t-test
sample_data = [12, 15, 14, 10, 13, 14, 15, 16, 14, 13]
population_mean = 13
t_stat_one,p_value_one = stats.ttest_1samp(sample_data, population_mean)
print("One-sample t-test:")
print(f"T-statistic = {t_stat_one:.4f}")
print(f"P-value = {p_value_one:.4f}")
if p_value_one < alpha:
    print("Conclusion: Reject the null hypothesis. No significant difference from the population mean.\n")
else:
    print("Conclusion: Fail to reject the null hypothesis. Significant difference from the population mean.\n")

# Two-sample t-test
group1 = [23, 21, 19, 24, 25]
group2 = [27, 29, 26, 30, 28]
t_stat_two, p_value_two = stats.ttest_ind(group1, group2, equal_var=True)
print("Two-sample t-test (Independent samples, equal variances):")
print(f"T-statistic = {t_stat_two:.4f}")
print(f"P-value = {p_value_two:.4f}")
if p_value_two < alpha:
    print("Conclusion: Reject the null hypothesis. There is a significant difference between the groups means.\n")
else:
    print("Conclusion: Fail to reject the null hypothesis. No significant difference between the groups means.\n")

One-sample t-test:
T-statistic = 1.1078
P-value = 0.2967
Conclusion: Fail to reject the null hypothesis. Significant difference from the population mean.

Two-sample t-test (Independent samples, equal variances):
T-statistic = -4.3464
P-value = 0.0025
Conclusion: Reject the null hypothesis. There is a significant difference between the groups means.



In [2]:
#Chi-Square Test
import numpy as np
from scipy.stats import chi2_contingency
# Create a contingency table
observed = np.array([
    [35, 52.5, 12.5], #Blue eyes
    [28.1, 42.1, 9.8], #Brown eyes
    [6.9, 10.4, 2.7] #Green eyes
])
chi2_stat, p_val, dof, expected = chi2_contingency(observed)
print("=== Chi-Square Test of Independence ===")
print(f"Chi-Square Statistic: {chi2_stat:.4f}")
print(f"Degrees of Freedom: {dof}")
print(f"P-value: {p_val:.4f}")
print("\nExpected Frequencies:")
print(expected)

=== Chi-Square Test of Independence ===
Chi-Square Statistic: 0.0230
Degrees of Freedom: 4
P-value: 0.9999

Expected Frequencies:
[[35.  52.5 12.5]
 [28.  42.  10. ]
 [ 7.  10.5  2.5]]


In [4]:
alpha = 0.05
if p_val < alpha:
    print("\nResult: Reject the null hypothesis")
    print("There is a statistically significant relationship between eye color and hair color")

else:
    print("\nResult: Fail to reject the null hypothesis")
    print("There is no statistically significant relationship")


Result: Fail to reject the null hypothesis
There is no statistically significant relationship


In [6]:
import numpy as np
from scipy.stats import chi2
observed = np.array([
    [30,10,10],
    [10,20,20]
])
row_total = observed.sum(axis=1)
col_total = observed.sum(axis=0)
grand_total = observed.sum()

expected = np.outer(row_total,col_total)/grand_total

chi2_stat = ((observed-expected)**2 / expected).sum()



In [9]:
dof =  (observed.shape[0]-1)*(observed.shape[1] -1)
p_val = 1-chi2.cdf(chi2_stat,dof)
print(chi2.cdf(chi2_stat,dof))
print("Chi_Square test of independence")
print(f"Chi_square statitcs = {chi2_stat:.4f}")
print(f"Degrees of freedom : {dof}")


0.9997596305235805
Chi_Square test of independence
Chi_square statitcs = 16.6667
Degrees of freedom : 2


In [12]:
print(f"P_value = {p_val:.4f}")
print("expected frequences")
print(expected)
alpha = 0.05
if p_val < alpha:
    print("Reject the synthesis: there is a significant association")

P_value = 0.0002
expected frequences
[[20. 15. 15.]
 [20. 15. 15.]]
Reject the synthesis: there is a significant association


In [ ]:
Preference = np.array([
    [40,60,100],
    [30,70,100],
    [70,130,200]
])
row_total = Preference.sum(axis=1)
col_total = Preference.sum(axis=0)
grand_total = Preference.sum()

expected = np.outer(row_total,col_total)/grand_total

chi2_stat = ((Preference-expected)**2 / expected).sum()
dof =  (Preference.shape[0]-1)*(Preference.shape[1] -1)
p_val = 1-chi2.cdf(chi2_stat,dof)
print(chi2.cdf(chi2_stat,dof))
print("Chi_Square test of independence")
print(f"Chi_square statitcs = {chi2_stat:.4f}")
print(f"Degrees of freedom : {dof}")
print(f"P_value = {p_val:.4f}")
print("expected frequences")
print(expected)
alpha = 0.05
if p_val < alpha:
    print("Reject the synthesis: there is a significant association")


0.30056833256221155
Chi_Square test of independence
Chi_square statitcs = 2.1978
Degrees of freedom : 4
P_value = 0.6994
expected frequences
[[ 35.  65. 100.]
 [ 35.  65. 100.]
 [ 70. 130. 200.]]
